spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 123456
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: user
    password: 123456
  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
